### ISSUE TITLE
The "Load from YouTube" button does not work (or does not respond)

### ISSUE THREAD

**Issue by Entity313** [NoobJsPerson/speedrun-timer#19]
Good afternoon. A year ago, I already came to you with the problem that "Load from YouTube" is not loading, the problem was solved by itself, or one of you solved the problem.
But now the problem has returned, but now it doesn’t react at all to pressing a button, if I add any link and even 1 text, there is no reaction, if nothing is written at all, then there is a reaction, but they ask to add a link, but for some reason this is only YouTube problem with uploading to Twitch everything works.
The problem appeared a week ago, I thought it would go away on its own, but no. I tried to solve the problem as before and in the end the same result as before.
I uploaded screenshots of evidence.
So please fix the problem.
Thank you in advance
![Screenshot_2023-02-26-18-45-43-787_com android chrome](https://user-images.githubusercontent.com/90765458/221425453-0d4c5f5d-7906-4c6b-9203-488ed3cf3c45.jpg)
![Screenshot_2023-02-26-18-56-25-304_com android chrome](https://user-images.githubusercontent.com/90765458/221425456-dc566eec-f18d-44aa-8484-b64500007758.jpg)

**Comment by Entity313** [comment]
I'm sorry, I just last used the site a year ago, which is why I closed the problem by accident.
I also want to add that I didn’t touch the Custom Mod Message 2 years ago from the moment I entered the speedrun timer and, as a result, didn’t touch anything.

**Comment by Entity313** [comment]
![Screenshot_2023-02-26-19-18-51-978_com android chrome](https://user-images.githubusercontent.com/90765458/221426379-610af160-3031-4758-b30d-db2e284a500b.jpg)

**Comment by Entity313** [comment]
И вот ссылка на сайт ваш который сейчас у меня: https://noobjsperson.github.io/speedrun-timer/

**Comment by NoobJsPerson** [comment]
Yeah i misspelled a variable in the code in one of my commits if you clear the website cache it will most likely work

**Comment by Entity313** [comment]
I again went to the site, the problem with the button finally went away, but now any video from YouTube does not respond, and if you immediately click on the video button, an identification error will appear o8Hk_peeov5jjxW.
(mainly look at the screenshots if you don’t understand what I’m talking about)
![Screenshot_2023-02-27-13-52-24-661_com android chrome](https://user-images.githubusercontent.com/90765458/221557827-b393465b-ff30-4202-881b-b9be86d07da9.jpg)
![Screenshot_2023-02-27-13-52-31-701_com android chrome](https://user-images.githubusercontent.com/90765458/221557829-de45ad2c-2068-4582-b2ae-b8c5aa1e6ebc.jpg)

**Comment by Entity313** [comment]
Please help me!
The problem was not completely resolved, I did it as you asked, but it didn’t help even through another browser, I went to your site!
There is a download to the site, but after the download the site no longer works!

**Comment by Entity313** [comment]
![Screenshot_2023-02-28-12-26-29-366_com android chrome](https://user-images.githubusercontent.com/90765458/221827147-ad83bc64-95e4-485b-a0d7-e760117aab1a.jpg)
![Screenshot_2023-02-28-12-26-32-747_com android chrome](https://user-images.githubusercontent.com/90765458/221827153-5e7f6f02-fa68-49db-9615-972ba260fa67.jpg)

**Comment by NoobJsPerson** [comment]
Ok i would look into this

**Comment by NoobJsPerson** [comment]
It should be fixed now. It was an issue with the regex being broken

**Comment by Entity313** [comment]
Did not help.
Nothing has changed in 2 browsers.
But when I immediately click on the video when I press the button, then the QaVj_c2bQKaGOMkk display error (that is, not the same as it was a few days ago)
![Screenshot_2023-03-01-19-06-30-845_com mi globalbrowser](https://user-images.githubusercontent.com/90765458/222211662-017a6a12-1b2b-4b84-a428-220bfbf29435.jpg)
![Screenshot_2023-03-01-19-06-25-673_com mi globalbrowser](https://user-images.githubusercontent.com/90765458/222211667-ecb69235-d586-4261-8eb5-604c10877b33.jpg)

**Comment by NoobJsPerson** [comment]
also dont forget to delete the site's browsing data again

**Comment by Entity313** [comment]
Here is the link: https://youtu.be/RTSCA6GB8ds
But I tried many youtube links and same result.

**Comment by Entity313** [comment]
Everything finally helped!
You were right for the cache, it turns out I didn’t clean it.
I’ll try to clarify with a translator (how I solved the problem on my phone chome): go to 3 points, go to history, clear history, advanced (it’s important if you choose another problem is not solved, since another tab clears the browser history), select all the time or the time when the site was used , and after that we clean the history and check.
Help for phone users.
For a PC, as I think, you need to go into the history in the expanded ones and clean it already there.
And thanks for the help for solving the problem, if I immediately understood or explained to me how to clear the cache, then it would not take such a long time.
![Screenshot_2023-03-11-21-12-42-385_com android chrome](https://user-images.githubusercontent.com/90765458/224507841-fd8e7b17-c2da-4920-9a05-79689b885e25.jpg)
![Screenshot_2023-03-11-21-12-47-811_com android chrome](https://user-images.githubusercontent.com/90765458/224507842-f87c0b21-0ea2-46a9-aab1-df919c5a1e80.jpg)
![Screenshot_2023-03-11-21-13-00-658_com android chrome](https://user-images.githubusercontent.com/90765458/224507844-bb4fe2ce-be29-49a8-8faa-524ee222bc4d.jpg)

**Comment by NoobJsPerson** [comment]
Sorry i thought you knew how to do it but its better now that you explained it so it won't be confusing to others
